### PR TITLE
List all member by API

### PR DESCRIPTION
**Pull request by iach526526**
## Summary by CodeRabbit

- **New Features**
	- Added automated code formatting using the Black formatter to improve code consistency.
	- Introduced a new API endpoint `/api/mlist` for retrieving members from a Discord guild.

- **Updates**
	- Updated naming conventions in the GitHub Actions workflow for Pylint to enhance readability.

- **Style**
	- Improved readability of the codebase with consistent formatting adjustments across multiple files.

### CODE REVIEW

**Comment by winstonsung** [comment]
Rebase! Rebase! Rebase! Don't create merge commits!

@iach526526

**Comment by winstonsung** [comment]
```bash
git config pull.rebase true
```

@iach526526

**Review by Edit-Mr — APPROVED** [review]

**Comment by Edit-Mr** [comment]
@winstonsung 你這樣算改好了嗎?

**Comment by Edit-Mr** [comment]
先這樣吧，趕時間

**Comment by winstonsung** [comment]
好了，Black有正常運作了。

**Comment by winstonsung** [comment]
（CI過了就是有正常。）

**Pull request merged**
